-- Migration Version: 000002
-- Description: Transaction Service domain table (transactions)
-- Dependencies: Requires migration 000001 (outbox_events + CDC)

-- ============================================
-- Table: transactions
-- Purpose: Orchestrate business transactions (TRANSFER, WITHDRAWAL, PURCHASE)
-- Mutable: YES - Status transitions (PENDING → COMPLETED/FAILED)
-- Relationships: References Account/Card/Ledger via IDs (microservice boundary - no FK!)
-- Event Sourcing: State changes trigger events via outbox pattern
-- Concurrency: Optimistic locking via version column
-- ============================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'transactions' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.transactions (
        -- ============================================
        -- Primary Key
        -- id: UUID generated by application
        -- Format: txn-{uuid}
        -- Example: txn-550e8400-e29b-41d4-a716-446655440000
        -- ============================================
        id NVARCHAR(50) NOT NULL PRIMARY KEY,
        
        -- ============================================
        -- Idempotency (CRITICAL for Duplicate Prevention)
        -- idempotency_key: Client-provided UUID
        -- Frontend generates UUID once, retries use same key
        -- Prevents double-processing on network failures
        -- UNIQUE constraint enforces idempotency at DB level
        -- Example: 550e8400-e29b-41d4-a716-446655440000
        -- ============================================
        idempotency_key NVARCHAR(100) NOT NULL,
        
        -- ============================================
        -- Transaction Classification
        -- transaction_type: Business category
        --   TRANSFER: Account-to-account money transfer
        --   WITHDRAWAL: ATM cash withdrawal (requires debit card + PIN)
        --   PURCHASE: Merchant payment via card (POS or online)
        -- CHECK constraint ensures only valid types
        -- ============================================
        transaction_type NVARCHAR(20) NOT NULL,
        
        -- ============================================
        -- Transaction Status (State Machine)
        -- PENDING: Created, validation in progress
        -- COMPLETED: Ledger confirmed success (TransactionPostedEvent received)
        -- FAILED: Validation failed or Ledger rejected
        -- 
        -- Transitions:
        --   PENDING → COMPLETED (normal flow)
        --   PENDING → FAILED (validation error / ledger error)
        -- 
        -- NOTE: No CANCELLED status (use FAILED with reason=USER_CANCELLED)
        -- ============================================
        status NVARCHAR(20) NOT NULL,
        
        -- ============================================
        -- Financial Information
        -- total_amount: Transaction amount (always positive)
        -- currency: ISO 4217 currency code
        -- 
        -- IMPORTANT: Must use DECIMAL(19,4) for financial precision
        -- Never use FLOAT or DOUBLE for money!
        -- 
        -- Current System: Only TRY supported (no multi-currency)
        -- Future: Can add USD, EUR when Exchange Service is ready
        -- ============================================
        total_amount DECIMAL(19, 4) NOT NULL,
        currency NVARCHAR(3) NOT NULL DEFAULT 'TRY',
        
        -- ============================================
        -- Account References (Microservice Boundaries)
        -- from_account_id: Source account (Account Service)
        -- to_account_id: Destination account (Account Service)
        -- 
        -- NULL Scenarios:
        --   TRANSFER: Both NOT NULL
        --   WITHDRAWAL: from_account_id NOT NULL, to_account_id NULL (ATM has no account)
        --   PURCHASE: from_account_id NOT NULL, to_account_id NULL (merchant has no account)
        -- 
        -- NOTE: No foreign keys (microservice architecture)
        -- ============================================
        from_account_id NVARCHAR(50),
        to_account_id NVARCHAR(50),
        
        -- ============================================
        -- Card Reference (Optional for Card-Based Transactions)
        -- card_id: Card used in transaction (Card Service)
        -- 
        -- NULL Scenarios:
        --   TRANSFER: NULL (no card involved)
        --   WITHDRAWAL: NOT NULL (debit card + PIN required)
        --   PURCHASE: NOT NULL (debit or virtual card)
        -- 
        -- NOTE: No foreign key (microservice architecture)
        -- ============================================
        card_id NVARCHAR(50),
        
        -- ============================================
        -- Merchant Information (for PURCHASE transactions only)
        -- merchant_name: Store/website name (e.g., "Amazon", "Starbucks")
        -- merchant_category: Business type (e.g., "E-commerce", "Restaurant")
        -- is_online: Online (true) vs Physical POS (false)
        -- 
        -- NULL for TRANSFER and WITHDRAWAL
        -- ============================================
        merchant_name NVARCHAR(200),
        merchant_category NVARCHAR(50),
        is_online BIT DEFAULT 0,
        
        -- ============================================
        -- ATM Information (for WITHDRAWAL transactions only)
        -- atm_id: ATM machine identifier (e.g., "ATM-001", "ATM-KADIKOY-01")
        -- location: Physical location (e.g., "Kadıköy Şubesi", "İstiklal Caddesi")
        -- 
        -- NULL for TRANSFER and PURCHASE
        -- ============================================
        atm_id NVARCHAR(50),
        location NVARCHAR(200),
        
        -- ============================================
        -- Business Metadata
        -- description: User-provided transaction note
        --   Example: "Kira ödemesi", "Market alışverişi"
        -- initiator_id: Customer ID who created the transaction (audit)
        -- reference_number: Unique business reference
        --   Format: {TYPE}-{YYYYMMDD}-{SEQ}
        --   Example: TRF-20251221-001, WTH-20251221-042, PUR-20251221-128
        --   Used for:
        --     - Ledger correlation (ledger_entries.reference_number)
        --     - Customer support / reconciliation
        --   UNIQUE constraint prevents duplicate reference numbers
        -- ============================================
        description NVARCHAR(500),
        initiator_id NVARCHAR(50),
        reference_number NVARCHAR(100) NOT NULL,
        
        -- ============================================
        -- Ledger Integration (Event-Driven)
        -- posting_date: Accounting date (business day, YYYY-MM-DD)
        -- value_date: Value date for interest calculation (YYYY-MM-DD)
        -- ledger_transaction_id: Transaction ID in Ledger Service
        -- 
        -- Lifecycle:
        --   1. Transaction created → these are NULL
        --   2. TransactionStartedEvent published → posting_date, value_date set
        --   3. TransactionPostedEvent received → ledger_transaction_id set
        -- 
        -- NOTE: These match Ledger Service's ledger_transactions table
        -- ============================================
        posting_date DATE,
        value_date DATE,
        ledger_transaction_id NVARCHAR(100),
        
        -- ============================================
        -- Timestamps (Full Audit Trail)
        -- created_at: When transaction was initiated by user
        -- completed_at: When Ledger confirmed success (TransactionPostedEvent received)
        -- failed_at: When validation or Ledger failed
        -- 
        -- Exactly one of (completed_at, failed_at) will be NOT NULL for non-PENDING transactions
        -- ============================================
        created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
        completed_at DATETIME2,
        failed_at DATETIME2,
        
        -- ============================================
        -- Failure Information (populated only if status=FAILED)
        -- failure_reason: Error code for programmatic handling
        --   Examples:
        --     INSUFFICIENT_FUNDS
        --     ACCOUNT_INACTIVE
        --     CARD_BLOCKED
        --     INVALID_PIN
        --     LIMIT_EXCEEDED
        --     LEDGER_ERROR
        -- 
        -- failure_details: Human-readable error message
        --   Example: "Available balance (500.00 TRY) insufficient for amount (1000.00 TRY)"
        -- 
        -- failed_step: Which step failed (debugging)
        --   Examples:
        --     VALIDATION (account/card validation failed)
        --     BALANCE_CHECK (insufficient funds)
        --     CARD_AUTHORIZATION (card authorize endpoint failed)
        --     LEDGER_POSTING (TransactionPostedEvent failed)
        -- 
        -- All NULL if status != FAILED
        -- ============================================
        failure_reason NVARCHAR(100),
        failure_details NVARCHAR(1000),
        failed_step NVARCHAR(50),
        
        -- ============================================
        -- Optimistic Locking (Concurrency Control)
        -- version: Incremented on each UPDATE
        -- Prevents race conditions during status updates
        -- 
        -- Scenario: Two threads try to update same transaction
        --   Thread A reads transaction (version=0)
        --   Thread B reads transaction (version=0)
        --   Thread A updates (WHERE version=0), sets version=1 → SUCCESS
        --   Thread B updates (WHERE version=0), sets version=1 → FAIL (version already 1)
        -- 
        -- JPA @Version annotation handles this automatically
        -- ============================================
        version BIGINT NOT NULL DEFAULT 0,
        
        -- ============================================
        -- Constraints
        -- ============================================
        CONSTRAINT UQ_transactions_idempotency_key UNIQUE (idempotency_key),
        CONSTRAINT UQ_transactions_reference_number UNIQUE (reference_number),
        CONSTRAINT CK_transactions_type CHECK (transaction_type IN ('TRANSFER', 'WITHDRAWAL', 'PURCHASE')),
        CONSTRAINT CK_transactions_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
        CONSTRAINT CK_transactions_amount_positive CHECK (total_amount > 0),
        
        -- ============================================
        -- Indexes for Performance
        -- Design Rationale:
        --   1. Customer wants to see their transaction history → initiator_id
        --   2. Account statement needs transactions → from_account_id/to_account_id
        --   3. Card transactions report → card_id
        --   4. Admin dashboard filters by status/type
        --   5. Most queries want recent transactions first → created_at DESC
        -- ============================================
        
        -- Single-column indexes
        INDEX IX_transactions_from_account (from_account_id),
        INDEX IX_transactions_to_account (to_account_id),
        INDEX IX_transactions_card (card_id),
        INDEX IX_transactions_status (status),
        INDEX IX_transactions_type (transaction_type),
        INDEX IX_transactions_initiator (initiator_id),
        INDEX IX_transactions_created_desc (created_at DESC),
        INDEX IX_transactions_posting_date (posting_date),
        
        -- Composite indexes (covering common query patterns)
        -- Query: "Show COMPLETED transactions for account X"
        INDEX IX_transactions_from_account_status (from_account_id, status),
        
        -- Query: "Transaction history for account X ordered by date"
        INDEX IX_transactions_from_account_created (from_account_id, created_at DESC),
        
        -- Query: "Customer's transactions by status"
        INDEX IX_transactions_initiator_status (initiator_id, status),
        
        -- Query: "PENDING transactions for monitoring/retry"
        INDEX IX_transactions_status_created (status, created_at DESC)
    );
    
    PRINT 'Table transactions created successfully';
    PRINT '  - Transaction orchestration (TRANSFER, WITHDRAWAL, PURCHASE)';
    PRINT '  - Idempotency via unique key (prevents duplicates)';
    PRINT '  - References Account, Card, Ledger via IDs (no FK)';
    PRINT '  - Event-driven integration (outbox pattern)';
    PRINT '  - Optimistic locking (version column)';
    PRINT '  - Comprehensive indexing (12 indexes for query performance)';
    PRINT '  - Audit trail (created_at, completed_at, failed_at)';
    PRINT '  - Failure tracking (reason, details, step)';
END
ELSE
BEGIN
    PRINT 'Table transactions already exists - skipping';
END;
-- GO command removed (not supported by migration tool)

-- ============================================
-- Verification: Check table created
-- ============================================
PRINT '';
PRINT '========================================';
PRINT 'Migration 000002 completed successfully';
PRINT '========================================';
PRINT 'Tables created:';
PRINT '  1. transactions (business transaction orchestration)';
PRINT '';
PRINT 'Schema Design Notes:';
PRINT '  ✓ Single table (no split like Ledger) - Transaction Service is orchestrator only';
PRINT '  ✓ Idempotency enforced at DB level (unique constraint)';
PRINT '  ✓ Reference number correlation with Ledger Service';
PRINT '  ✓ Type-specific fields (merchant, ATM) are nullable';
PRINT '  ✓ Status machine: PENDING → COMPLETED/FAILED';
PRINT '  ✓ Full audit trail with 3 timestamps';
PRINT '  ✓ Failure tracking for debugging';
PRINT '  ✓ Optimistic locking prevents race conditions';
PRINT '  ✓ 12 indexes optimized for common queries';
PRINT '  ✓ No foreign keys (microservice boundaries)';
PRINT '  ✓ DECIMAL(19,4) for financial precision';
PRINT '';
PRINT 'Integration:';
PRINT '  → Account Service: from_account_id, to_account_id';
PRINT '  → Card Service: card_id';
PRINT '  → Ledger Service: ledger_transaction_id, reference_number';
PRINT '  → Events via outbox_events (created in 000001)';
PRINT '========================================';
-- GO command removed (not supported by migration tool)

-- ============================================
-- Quick Sanity Check Query
-- ============================================
SELECT 
    'Table Structure Verification' AS CheckType,
    t.name AS TableName,
    c.name AS ColumnName,
    TYPE_NAME(c.user_type_id) AS DataType,
    c.max_length AS MaxLength,
    c.is_nullable AS IsNullable
FROM sys.tables t
JOIN sys.columns c ON t.object_id = c.object_id
WHERE t.schema_id = SCHEMA_ID('dbo')
  AND t.name = 'transactions'
ORDER BY c.column_id;

SELECT 
    'Index Verification' AS CheckType,
    t.name AS TableName,
    i.name AS IndexName,
    i.type_desc AS IndexType,
    i.is_unique AS IsUnique,
    COL_NAME(ic.object_id, ic.column_id) AS ColumnName
FROM sys.tables t
JOIN sys.indexes i ON t.object_id = i.object_id
LEFT JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id
WHERE t.schema_id = SCHEMA_ID('dbo')
  AND t.name = 'transactions'
  AND i.name IS NOT NULL
ORDER BY i.index_id, ic.index_column_id;

SELECT 
    'Constraint Verification' AS CheckType,
    t.name AS TableName,
    con.name AS ConstraintName,
    con.type_desc AS ConstraintType
FROM sys.tables t
JOIN sys.check_constraints con ON t.object_id = con.parent_object_id
WHERE t.schema_id = SCHEMA_ID('dbo')
  AND t.name = 'transactions'
UNION ALL
SELECT 
    'Constraint Verification' AS CheckType,
    t.name AS TableName,
    kc.name AS ConstraintName,
    'UNIQUE' AS ConstraintType
FROM sys.tables t
JOIN sys.key_constraints kc ON t.object_id = kc.parent_object_id
WHERE t.schema_id = SCHEMA_ID('dbo')
  AND t.name = 'transactions'
  AND kc.type = 'UQ'
ORDER BY TableName, ConstraintName;
-- GO command removed (not supported by migration tool)
