-- Migration Version: 000002
-- Description: Account Service domain tables (Products, Accounts)
-- Dependencies: Requires migration 000001 (outbox_events + CDC)

-- ============================================
-- Table 1: product_definitions
-- Purpose: Reference table for account product catalog
-- Mutable: YES - Products can be updated/disabled
-- Examples: RETAIL_TRY (Checking), GOLD_ACC (Savings), CREDIT_STD (Credit Card)
-- ============================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'product_definitions' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.product_definitions (
        -- ============================================
        -- Primary Key
        -- code: Unique product identifier (e.g., RETAIL_TRY, GOLD_ACC)
        -- ============================================
        code NVARCHAR(50) NOT NULL PRIMARY KEY,
        
        -- ============================================
        -- Product Information
        -- name: Human-readable product name for UI
        -- category: Product type - CHECKING, SAVINGS, or CREDIT
        -- features: JSON object storing product rules, limits, and configuration
        -- ============================================
        name NVARCHAR(100) NOT NULL,
        category NVARCHAR(50) NOT NULL,
        features NVARCHAR(MAX) NULL,
        
        -- ============================================
        -- Lifecycle Management
        -- is_active: Soft delete flag - inactive products cannot be assigned to new accounts
        -- ============================================
        is_active BIT DEFAULT 1,
        
        -- ============================================
        -- Audit Fields
        -- ============================================
        created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2 NULL,
        
        -- ============================================
        -- Indexes for Performance
        -- - category: Filter products by type
        -- - is_active: Find available products for new accounts
        -- ============================================
        INDEX IX_product_definitions_category (category),
        INDEX IX_product_definitions_active (is_active)
    );
    
    PRINT 'Table product_definitions created successfully';
    PRINT '  - Product catalog for account types';
    PRINT '  - Supports CHECKING, SAVINGS, CREDIT categories';
    PRINT '  - Features stored as JSON for flexibility';
END
ELSE
BEGIN
    PRINT 'Table product_definitions already exists - skipping';
END;
-- GO command removed (not supported by migration tool)

-- ============================================
-- Table 2: accounts
-- Purpose: Customer account records
-- Mutable: YES - Account status, balance, and configuration can change
-- Relationships: References product_definitions via product_code
-- Event Sourcing: State changes trigger events via outbox pattern
-- ============================================
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'accounts' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.accounts (
        -- ============================================
        -- Primary Key
        -- id: UUID generated by application
        -- ============================================
        id NVARCHAR(36) NOT NULL PRIMARY KEY,
        
        -- ============================================
        -- Owner Information
        -- customer_id: References customer in Customer Service (microservice boundary - no FK!)
        -- account_number: IBAN or unique account identifier
        -- ============================================
        customer_id NVARCHAR(50) NOT NULL,
        account_number NVARCHAR(50) NOT NULL,
        
        -- ============================================
        -- Product Relationship
        -- product_code: Foreign key to product_definitions
        -- Defines account type, rules, and features
        -- ============================================
        product_code NVARCHAR(50) NOT NULL,
        
        -- ============================================
        -- Financial Information
        -- currency: ISO 4217 currency code (TRY, USD, EUR, XAU, etc.)
        -- balance: Current balance projection (updated from ledger service events)
        -- Must use DECIMAL for financial precision (never float/double!)
        -- ============================================
        currency NVARCHAR(3) NOT NULL DEFAULT 'TRY',
        balance DECIMAL(19, 4) NOT NULL DEFAULT 0.0,
        
        -- ============================================
        -- Account Status
        -- status: ACTIVE, CLOSED, FROZEN, PENDING
        -- Status changes trigger events to ledger service
        -- ============================================
        status NVARCHAR(20) NOT NULL,
        
        -- ============================================
        -- Configuration
        -- configurations: JSON object for account-specific settings
        -- Examples: overdraft limits, fee waiver flags, statement preferences
        -- ============================================
        configurations NVARCHAR(MAX) NULL,
        
        -- ============================================
        -- Optimistic Locking (Concurrency Control)
        -- version: Incremented on each update
        -- Prevents race conditions when multiple transactions update same account simultaneously
        -- ============================================
        version BIGINT DEFAULT 0,
        
        -- ============================================
        -- Audit Fields
        -- ============================================
        created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
        updated_at DATETIME2 NULL,
        
        -- ============================================
        -- Foreign Key to Product Catalog
        -- ============================================
        CONSTRAINT FK_accounts_product 
            FOREIGN KEY (product_code) 
            REFERENCES dbo.product_definitions(code),
        
        -- ============================================
        -- Unique Constraints
        -- account_number: Must be globally unique (IBAN or bank-specific format)
        -- ============================================
        CONSTRAINT UQ_accounts_number UNIQUE (account_number),
        
        -- ============================================
        -- Indexes for Performance
        -- - customer_id: Find all accounts for a customer
        -- - product_code: Find all accounts of a specific product type
        -- - status: Filter by account status
        -- - customer_status: Composite index for customer's active accounts
        -- ============================================
        INDEX IX_accounts_customer_id (customer_id),
        INDEX IX_accounts_product_code (product_code),
        INDEX IX_accounts_status (status),
        INDEX IX_accounts_customer_status (customer_id, status)
    );
    
    PRINT 'Table accounts created successfully';
    PRINT '  - Customer account management';
    PRINT '  - Foreign key to product_definitions';
    PRINT '  - Optimistic locking enabled (version column)';
    PRINT '  - Balance projection from ledger service';
END
ELSE
BEGIN
    PRINT 'Table accounts already exists - skipping';
END;
-- GO command removed (not supported by migration tool)

-- ============================================
-- Seed Data: Product Definitions
-- Purpose: Initialize catalog with standard product types
-- Note: These are reference products, banks can add custom products later
-- ============================================
IF NOT EXISTS (SELECT 1 FROM dbo.product_definitions WHERE code = 'RETAIL_TRY')
BEGIN
    INSERT INTO dbo.product_definitions (code, name, category, features, is_active)
    VALUES 
        (
            'RETAIL_TRY', 
            'Vadesiz TL Hesabı', 
            'CHECKING', 
            '{"currency":"TRY","allow_negative":true,"interest_rate":0.0,"monthly_fee":0.0}',
            1
        ),
        (
            'SAVINGS_USD', 
            'USD Tasarruf Hesabı', 
            'SAVINGS', 
            '{"currency":"USD","allow_negative":false,"interest_rate":2.5,"monthly_fee":0.0,"minimum_balance":100.0}',
            1
        ),
        (
            'GOLD_ACC', 
            'Altın Hesabı', 
            'SAVINGS', 
            '{"currency":"XAU","allow_negative":false,"interest_rate":0.0,"monthly_fee":5.0,"purity":995}',
            1
        ),
        (
            'CREDIT_STD', 
            'Standart Kredi Kartı', 
            'CREDIT', 
            '{"currency":"TRY","billing_cycle":30,"limit_default":5000.0,"interest_rate":3.99,"grace_period":45}',
            1
        );
    
    PRINT 'Seed data inserted into product_definitions';
    PRINT '  - RETAIL_TRY: Turkish Lira checking account';
    PRINT '  - SAVINGS_USD: USD savings account with interest';
    PRINT '  - GOLD_ACC: Gold account (measured in troy ounces)';
    PRINT '  - CREDIT_STD: Standard credit card';
END
ELSE
BEGIN
    PRINT 'Seed data already exists in product_definitions - skipping';
END;
-- GO command removed (not supported by migration tool)

-- ============================================
-- Verification: Check all tables created
-- ============================================
PRINT '';
PRINT '========================================';
PRINT 'Migration 000002 completed successfully';
PRINT '========================================';
PRINT 'Tables created:';
PRINT '  1. product_definitions (reference data)';
PRINT '  2. accounts (domain entities)';
PRINT '';
PRINT 'Notes:';
PRINT '  - outbox_events already exists (created in 000001)';
PRINT '  - Account state changes must publish events to outbox_events';
PRINT '  - Balance is projection from ledger service (event-driven)';
PRINT '  - All monetary amounts use DECIMAL(19,4) for precision';
PRINT '  - Foreign key: accounts->product_definitions';
PRINT '========================================';
-- GO command removed (not supported by migration tool)

-- ============================================
-- Quick Sanity Check Query
-- ============================================
SELECT 
    t.name AS TableName,
    i.name AS IndexName,
    i.type_desc AS IndexType
FROM sys.tables t
LEFT JOIN sys.indexes i ON t.object_id = i.object_id
WHERE t.schema_id = SCHEMA_ID('dbo')
  AND t.name IN ('product_definitions', 'accounts', 'outbox_events')
  AND i.name IS NOT NULL
ORDER BY t.name, i.index_id;
-- GO command removed (not supported by migration tool)
